import {
  ElCarousel,
  ElCarouselItem,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElButton,
  ElForm,
  ElFormItem,
  ElOption,
  ElSelect,
  ElInput,
  ElCheckbox,
  ElPopover,
  ElRadio,
  ElRadioGroup,
  ElPagination,
  ElLoading,
  ElDialog,
  ElImage,
  ElUpload
} from 'element-plus'

const components = [
  ElCarousel,
  ElCarouselItem,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElButton,
  ElForm,
  ElFormItem,
  ElOption,
  ElSelect,
  ElInput,
  ElCheckbox,
  ElPopover,
  ElRadio,
  ElRadioGroup,
  ElPagination,
  ElImage,
  // ElAlert,
  // ElAside,
  // ElAutocomplete,
  // ElAvatar,
  // ElBacktop,
  // ElBreadcrumb,
  // ElBreadcrumbItem,
  // ElButtonGroup,
  // ElCalendar,
  // ElCard,
  // ElCarousel,
  // ElCarouselItem,
  // ElCascader,
  // ElCascaderPanel,
  // ElCheckboxButton,
  // ElCheckboxGroup,
  // ElCol,
  // ElCollapse,
  // ElCollapseItem,
  // ElCollapseTransition,
  // ElColorPicker,
  // ElContainer,
  // ElDatePicker,
  ElDialog,
  // ElDivider,
  // ElDrawer,
  // ElDropdown,
  // ElDropdownItem,
  // ElDropdownMenu,
  // ElFooter,
  // ElHeader,
  // ElIcon,
  // ElImage,
  // ElInputNumber,
  // ElLink,
  // ElMain,
  // ElMenu,
  // ElMenuItem,
  // ElMenuItemGroup,
  // ElOptionGroup,
  // ElPageHeader,
  // ElPopconfirm,
  // ElPopover,
  // ElPopper,
  // ElProgress,
  // ElRadioButton,
  // ElRate,
  // ElRow,
  // ElScrollbar,
  // ElSlider,
  // ElStep,
  // ElSteps,
  // ElSubmenu,
  // ElSwitch,
  // ElTabPane,
  // ElTable,
  // ElTableColumn,
  // ElTabs,
  // ElTag,
  // ElTimePicker,
  // ElTimeSelect,
  // ElTimeline,
  // ElTimelineItem,
  // ElTooltip,
  // ElTransfer,
  // ElTree,
  ElUpload
]

const plugins = [
  // ElInfiniteScroll,
  ElLoading
  // ElMessage,
  // ElMessageBox,
  // ElNotification
]

const setupElementPlus = (app) => {
  components.forEach(component => {
    app.component(component.name, component)
  })
  plugins.forEach(plugin => {
    app.use(plugin)
  })
}

export default setupElementPlus
